import gradio as gr

from app.graph_workflow import build_support_graph


# Build the LangGraph workflow once when app starts.
support_graph = build_support_graph()


def run_customer_support_workflow(customer_message: str) -> str:
    # Validate user input.
    if not customer_message or not customer_message.strip():
        return "Please enter a customer support message."

    # Initial state passed into the graph.
    initial_state = {
        "customer_message": customer_message,
        "category": "",
        "priority": "",
        "sentiment": "",
        "policy_guidance": "",
        "draft_response": "",
        "escalation_needed": "",
        "final_response": "",
    }

    # Invoke the LangGraph workflow.
    final_state = support_graph.invoke(initial_state)

    # Return final response generated by graph.
    return final_state["final_response"]


with gr.Blocks() as demo:
    # Page title.
    gr.Markdown("# Customer Support Workflow — LangGraph")

    # Page description.
    gr.Markdown(
        "A stateful support workflow with classification, policy lookup, response generation, and conditional escalation."
    )

    # Customer message input.
    customer_input = gr.Textbox(
        label="Customer Message",
        placeholder=(
            "Example: I was charged twice this month and I need a refund immediately."
        ),
        lines=10,
    )

    # Run workflow button.
    run_button = gr.Button("Run Support Workflow")

    # Output display.
    output = gr.Markdown(label="Workflow Output")

    # Connect button to workflow function.
    run_button.click(
        fn=run_customer_support_workflow,
        inputs=customer_input,
        outputs=output,
    )


if __name__ == "__main__":
    # Launch Gradio app locally.
    demo.launch()