from typing import TypedDict

from langgraph.graph import StateGraph, START, END

from app.llm_service import call_llm

from app.policies import lookup_support_policy

from app.prompts import (
    build_classification_prompt,
    build_response_prompt,
    build_escalation_prompt,
)

#create the structure of the workflow memory i.e the state has customer-message, categorey etc. 
# This class is passed as state. SO state will contain this structure
class SupportState(TypedDict):
    # Original customer message.
    customer_message: str

    # Ticket category detected by AI.
    category: str

    # Ticket priority detected by AI.
    priority: str

    # Customer emotional tone.
    sentiment: str

    # Policy guidance from deterministic policy lookup.
    policy_guidance: str

    # Draft response generated by AI.
    draft_response: str

    # Whether ticket needs human escalation.
    escalation_needed: str

    # Final response shown to user.
    final_response: str


def parse_classification_output(classification_text: str) -> dict:
    # Default values protect the workflow if AI output is imperfect.
    parsed = {
        "category": "General Inquiry",
        "priority": "Medium",
        "sentiment": "Confused",
    }

    # Split AI output into lines.
    lines = classification_text.splitlines()

    # Read each line and extract values.
    for line in lines:
        if line.lower().startswith("category:"):
            parsed["category"] = line.split(":", 1)[1].strip()

        elif line.lower().startswith("priority:"):
            parsed["priority"] = line.split(":", 1)[1].strip()

        elif line.lower().startswith("sentiment:"):
            parsed["sentiment"] = line.split(":", 1)[1].strip()

    # Return parsed dictionary.
    return parsed


def classify_ticket_node(state: SupportState) -> dict:
    # Build prompt for classifying the customer ticket.
    prompt = build_classification_prompt(
        customer_message=state["customer_message"]
    )

    # System prompt controls the AI behavior for classification.
    system_prompt = "You are an expert customer support classifier."

    # Call the LLM.
    classification_output = call_llm(
        system_prompt=system_prompt,
        user_prompt=prompt,
    )

    # Parse classification text into structured values.
    parsed = parse_classification_output(classification_output)

    # Return partial state update.
    return {
        "category": parsed["category"],
        "priority": parsed["priority"],
        "sentiment": parsed["sentiment"],
    }


def lookup_policy_node(state: SupportState) -> dict:
    # Lookup support policy based on ticket category.
    policy_guidance = lookup_support_policy(
        category=state["category"]
    )

    # Return policy guidance into workflow state.
    return {
        "policy_guidance": policy_guidance
    }


def generate_response_node(state: SupportState) -> dict:
    # Build prompt for support response generation.
    prompt = build_response_prompt(
        customer_message=state["customer_message"],
        category=state["category"],
        priority=state["priority"],
        policy_guidance=state["policy_guidance"],
    )

    # System prompt controls response-writing behavior.
    system_prompt = "You are a professional customer support specialist."

    # Call the LLM to generate draft response.
    draft_response = call_llm(
        system_prompt=system_prompt,
        user_prompt=prompt,
    )

    # Return draft response into state.
    return {
        "draft_response": draft_response
    }


def escalation_check_node(state: SupportState) -> dict:
    # Build prompt to determine whether human escalation is needed.
    prompt = build_escalation_prompt(
        customer_message=state["customer_message"],
        category=state["category"],
        priority=state["priority"],
        draft_response=state["draft_response"],
    )

    # System prompt controls escalation decision behavior.
    system_prompt = "You are a senior customer support operations manager."

    # Call the LLM.
    escalation_output = call_llm(
        system_prompt=system_prompt,
        user_prompt=prompt,
    )

    # Normalize escalation answer.
    escalation_needed = escalation_output.strip().upper()

    # If AI returns anything unexpected, default to NO.
    if escalation_needed not in ["YES", "NO"]:
        escalation_needed = "NO"

    # Return escalation decision into state.
    return {
        "escalation_needed": escalation_needed
    }


def human_escalation_node(state: SupportState) -> dict:
    # Create final output for tickets that need human escalation.
    final_response = f"""
# Customer Support Workflow Result

## Category
{state["category"]}

## Priority
{state["priority"]}

## Sentiment
{state["sentiment"]}

## Policy Guidance
{state["policy_guidance"]}

## Draft Customer Response
{state["draft_response"]}

## Escalation Decision
Human escalation is required.

## Internal Note
Route this ticket to a human support specialist before sending final response.
"""

    # Return final response into state.
    return {
        "final_response": final_response
    }


def auto_resolve_node(state: SupportState) -> dict:
    # Create final output for tickets that can be auto-resolved.
    final_response = f"""
# Customer Support Workflow Result

## Category
{state["category"]}

## Priority
{state["priority"]}

## Sentiment
{state["sentiment"]}

## Policy Guidance
{state["policy_guidance"]}

## Customer Response
{state["draft_response"]}

## Escalation Decision
No human escalation required.
"""

    # Return final response into state.
    return {
        "final_response": final_response
    }


def route_after_escalation_check(state: SupportState) -> str:
    # Conditional routing function.
    # LangGraph uses this return value to decide the next node.

    if state["escalation_needed"] == "YES":
        return "human_escalation"

    return "auto_resolve"


def build_support_graph():
    # Create a LangGraph StateGraph using SupportState.
    workflow = StateGraph(SupportState)

    # Register each workflow node.
    workflow.add_node("classify_ticket", classify_ticket_node)
    workflow.add_node("lookup_policy", lookup_policy_node)
    workflow.add_node("generate_response", generate_response_node)
    workflow.add_node("escalation_check", escalation_check_node)
    workflow.add_node("human_escalation", human_escalation_node)
    workflow.add_node("auto_resolve", auto_resolve_node)

    # START means this is the first node in the graph.
    workflow.add_edge(START, "classify_ticket")

    # Normal edges define fixed execution order.
    workflow.add_edge("classify_ticket", "lookup_policy")
    workflow.add_edge("lookup_policy", "generate_response")
    workflow.add_edge("generate_response", "escalation_check")

    # Conditional edge chooses next node dynamically.
    workflow.add_conditional_edges(
        "escalation_check",
        route_after_escalation_check,
        {
            "human_escalation": "human_escalation",
            "auto_resolve": "auto_resolve",
        },
    )

    # Both final paths end the graph.
    workflow.add_edge("human_escalation", END)
    workflow.add_edge("auto_resolve", END)

    # Compile the graph into a runnable app.
    return workflow.compile()