import json

import gradio as gr

from app.guardrails import (
    validate_user_question,
    validate_sql_query,
)

from app.llm_service import call_llm

from app.mcp_client import call_internal_data_tool

from app.prompts import (
    build_sql_generation_prompt,
    build_summary_prompt,
)


def clean_sql_output(sql_text: str) -> str:
    """
    Clean SQL generated by the LLM.
    Removes markdown formatting and extra whitespace.
    """

    cleaned = sql_text.replace("```sql", "").replace("```", "")
    cleaned = cleaned.strip()

    return cleaned


async def run_internal_data_assistant(question: str) -> str:
    """
    Main assistant workflow:
    1. Validate user question
    2. Generate SQL using LLM
    3. Validate SQL
    4. Execute SQL through MCP tool
    5. Summarize results
    """

    # -------------------------------------------------
    # Validate User Question
    # -------------------------------------------------
    question_allowed, question_message = validate_user_question(question)

    if not question_allowed:
        return f"""
# Request Blocked

## Reason
{question_message}
"""

    # -------------------------------------------------
    # Build SQL Generation Prompt
    # -------------------------------------------------
    sql_prompt = build_sql_generation_prompt(question)

    sql_system_prompt = (
        "You are a safe SQL generation assistant. "
        "Generate ONLY read-only SQLite SELECT queries. "
        "Never generate INSERT, UPDATE, DELETE, DROP, ALTER, "
        "or CREATE statements."
    )

    # -------------------------------------------------
    # Generate SQL using LLM
    # -------------------------------------------------
    sql_query = call_llm(
        system_prompt=sql_system_prompt,
        user_prompt=sql_prompt
    )

    # Clean generated SQL
    sql_query = clean_sql_output(sql_query)

    # -------------------------------------------------
    # Validate SQL
    # -------------------------------------------------
    sql_allowed, sql_message = validate_sql_query(sql_query)

    if not sql_allowed:
        return f"""
# Request Blocked by SQL Guardrail

## Reason
{sql_message}

## Generated SQL

```sql
{sql_query}
```
"""

    # -------------------------------------------------
    # Execute SQL through MCP Tool
    # -------------------------------------------------
    try:
        tool_result = await call_internal_data_tool(sql_query)

    except Exception as e:
        return f"""
# MCP Tool Execution Failed

## Error
{str(e)}
"""

    # -------------------------------------------------
    # Format Tool Result
    # -------------------------------------------------
    try:
        parsed_tool_result = json.loads(tool_result)

        formatted_tool_result = json.dumps(
            parsed_tool_result,
            indent=2,
        )

    except Exception:
        formatted_tool_result = str(tool_result)

    # -------------------------------------------------
    # Build Summary Prompt
    # -------------------------------------------------
    summary_prompt = build_summary_prompt(
        question=question,
        sql_query=sql_query,
        query_result=formatted_tool_result,
    )

    summary_system_prompt = (
        "You are a safe internal data assistant. "
        "Summarize internal business data clearly and concisely "
        "without exposing sensitive information."
    )

    # -------------------------------------------------
    # Generate Final Summary
    # -------------------------------------------------
    final_summary = call_llm(
        system_prompt=summary_system_prompt,
        user_prompt=summary_prompt,
    )

    # -------------------------------------------------
    # Final Response
    # -------------------------------------------------
    return f"""
# Internal Data Assistant Result

---

## User Question

{question}

---

## Generated SQL

```sql
{sql_query}
```

---

## MCP Tool Result

```json
{formatted_tool_result}
```

---

## Business Summary

{final_summary}
"""


# =====================================================
# Gradio UI
# =====================================================

with gr.Blocks() as demo:

    # App Title
    gr.Markdown("# Internal Data Assistant — MCP + Guardrails")

    # App Description
    gr.Markdown(
        """
Ask business questions over internal sales data.

The assistant:
- Validates user input
- Generates safe SQL
- Applies SQL guardrails
- Executes queries through MCP tools
- Summarizes results using AI
"""
    )

    # User Input
    question_input = gr.Textbox(
        label="Business Question",
        placeholder="Example: What is the total completed sales amount by region?",
        lines=4,
    )

    # Submit Button
    run_button = gr.Button("Ask Internal Data Assistant")

    # Output Area
    output = gr.Markdown(label="Assistant Output")

    # Button Action
    run_button.click(
        fn=run_internal_data_assistant,
        inputs=question_input,
        outputs=output,
    )


# =====================================================
# Main
# =====================================================

if __name__ == "__main__":
    demo.launch()
